baseURL = "https://relogiclabs.github.io/JSchema-Java"
languageCode = "en-us"
title = "JSchema"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true